### ISSUE TITLE
`make` fails on poetry installation

### ISSUE THREAD

**Issue by OfekShilon** [compiler-explorer/infra#1141]
I'm trying to `make ce` on WSL. The direct error is:
```
...
You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.7.0): Creating environment
Poetry installation failed.
See /home/ofek/src/infra/poetry-installer-error-98f8o7ss.log for error logs.
```
The log says:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/poetry-installervl981brt/virtualenv.pyz/__main__.py", line 163, in <module>
  File "/tmp/poetry-installervl981brt/virtualenv.pyz/__main__.py", line 159, in run
  File "/tmp/poetry-installervl981brt/virtualenv.pyz/virtualenv/__main__.py", line 18, in run
  File "/tmp/poetry-installervl981brt/virtualenv.pyz/virtualenv/run/__init__.py", line 31, in cli_run
  File "/tmp/poetry-installervl981brt/virtualenv.pyz/virtualenv/run/__init__.py", line 49, in session_via_cli
  File "/tmp/poetry-installervl981brt/virtualenv.pyz/virtualenv/run/__init__.py", line 82, in build_parser
  File "/tmp/poetry-installervl981brt/virtualenv.pyz/virtualenv/run/plugin/creators.py", line 24, in __init__
  File "/tmp/poetry-installervl981brt/virtualenv.pyz/virtualenv/run/plugin/creators.py", line 31, in for_interpreter
  File "/tmp/poetry-installervl981brt/virtualenv.pyz/virtualenv/run/plugin/base.py", line 45, in options
  File "/tmp/poetry-installervl981brt/virtualenv.pyz/virtualenv/run/plugin/base.py", line 24, in entry_points_for
  File "/tmp/poetry-installervl981brt/virtualenv.pyz/virtualenv/run/plugin/base.py", line 24, in <genexpr>
  File "/usr/lib/python3.9/importlib/metadata.py", line 79, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'virtualenv.create.via_global_ref.builtin.cpython.mac_os' has no attribute 'CPython2macOsFramework'

Traceback:

  File "<stdin>", line 923, in main
  File "<stdin>", line 560, in run
  File "<stdin>", line 581, in install
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "<stdin>", line 653, in make_env
  File "<stdin>", line 639, in make_env
  File "<stdin>", line 341, in make
  File "<stdin>", line 365, in run
```

**Comment by mattgodbolt** [comment]
I'm not sure any of this works on WSL, unfortunately. If you have any ideas why I'll happily make changes, but I only have access to Linux machines (and that's all we run admin-like stuff on)

**Comment by OfekShilon** [comment]
Dumping it here in case it is of use to someone in the future:
[The problem was](https://stackoverflow.com/questions/72613928/module-virtualenv-create-via-global-ref-builtin-cpython-mac-os-has-no-attribut) that `virtualenv` was preinstalled and needed to be removed.
