### ISSUE TITLE
CUDA libs failing to install

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/infra#1158]
```
Nov/21 02:33 admin-node~/infra (main|✔) 11.4s $ sudo ce_install install cuda
2023-11-21 02:34:09,409 lib.installation_context INFO     Making uncached requests
2023-11-21 02:34:09,410 lib.ce_install  INFO     Creating multiprocessing pool with 2 workers
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ubuntu/infra/bin/lib/ce_install.py", line 378, in _should_install
    return installable, force or installable.should_install()
  File "/home/ubuntu/infra/bin/lib/installable/git.py", line 166, in should_install
    remote_hash = _remote_get_current_hash(self._logger, prior_installation, branch)
  File "/home/ubuntu/infra/bin/lib/installable/git.py", line 42, in _remote_get_current_hash
    raise RuntimeError(f"Unable to get remote hash for {git_repo}:{branch}")
RuntimeError: Unable to get remote hash for /opt/compiler-explorer/libs/nvtx/v3.0.1:v3.0.1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/ubuntu/infra/bin/lib/ce_install.py", line 380, in _should_install
    raise RuntimeError(f"Unable to install {installable}") from ex
RuntimeError: Unable to install GitHubInstallable(libraries/cuda/nvtx 3.0.1, libs/nvtx/v3.0.1)
"""
```

**Comment by mattgodbolt** [comment]
Looks like @partouf was last to touch this but was a reformat. I wonder if it was broken before? I don't recall seeing it before though our noticing of library install failures is woeful, so it could have been broken for a long while.
