### ISSUE TITLE
Error when running `ce_install.ps1` on windows

### ISSUE THREAD

**Issue by OfekShilon** [compiler-explorer/infra#1168]
The first problem is:
```
PS C:\Users\ofeks\source\repos\infra> ./ce_install.ps1 --staging-dir "C:\tmp\staging" --dest "C:\efs\compilers" --enable windows install windows
Get-Item : Cannot find path 'C:\Users\ofeks\source\repos\infra\.env' because it does not exist.
At C:\Users\ofeks\source\repos\infra\ce_install.ps1:6 char:9
+ if (! ((Get-Item .env) -as [bool])) {
+         ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\ofeks\source\repos\infra\.env:String) [Get-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand
```
This can be solved by checking for folder existence with `Test-Path` instead of `Get-Item`.

A second problem is:
```
PS C:\Users\ofeks\source\repos\infra> ./ce_install.ps1 --staging-dir "C:/tmp/staging" --dest "C:/efs/compilers" --enable windows install windows
  File "<string>", line 1
    import sys; sys.path.append('C:\Users\ofeks\source\repos\infra/bin'); from lib.ce_install import main; main()
```
Here the problem is that the backslashes in the path are interpreted by python as escapes. The string argument to `sys.path.append` needs to be prefixed with `r`.

I'm guessing the script doesn't actually run on windows as part of some CI. If it does then I'm missing something.

**Comment by OfekShilon** [comment]
This is by no means the end of the problems. After these two fixes the script runs and gives -
```
...
2023-11-26 00:33:15,904 lib.installation_context INFO     100% of https://github.com/compiler-explorer/ninja/releases/download/v1.12.1/ninja-win.zip
2023-11-26 00:33:15,905 lib.installation_context INFO     Staging with tar -xf 'C:\tmp\staging\5fc25019-ba49-4227-8732-f06f21e388c5\distribution.zip' -d bin
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
2023-11-26 00:33:15,934 lib.ce_install  INFO     windows/tools/ninja 1.12.1 failed to install: Command '['tar', '-xf', 'C:\\tmp\\staging\\5fc25019-ba49-4227-8732-f06f21e388c5\\distribution.zip', '-d', 'bin']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Users\ofeks\source\repos\infra/bin\lib\ce_install.py", line 400, in install
    installable.install()
  File "C:\Users\ofeks\source\repos\infra/bin\lib\installable\archives.py", line 315, in install
    self.stage(staging)
  File "C:\Users\ofeks\source\repos\infra/bin\lib\installable\archives.py", line 287, in stage
    self.install_context.stage_command(staging, unzip_cmd)
  File "C:\Users\ofeks\source\repos\infra/bin\lib\installation_context.py", line 155, in stage_command
    subprocess.check_call(command, cwd=str(cwd or staging.path), env=env)
  File "C:\Program Files\Python311\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tar', '-xf', 'C:\\tmp\\staging\\5fc25019-ba49-4227-8732-f06f21e388c5\\distribution.zip', '-d', 'bin']' returned non-zero exit status 1.
```

The `tar` command includes the switch `-d`, which comes from here: https://github.com/compiler-explorer/infra/blob/7a9b440f0854ec4ac26c4896d0d7f5b38b1c73dc/bin/lib/installable/archives.py#L286C64-L286C64


Not sure what it was meant to do. If it's for specifying a dest folder than it was probably supposed to be `-C`?  And if that dest folder is indeed `bin` the entire script should have been run from elsewhere?

**Comment by mattgodbolt** [comment]
Summoning @partouf as I am such a Windows noob

**Comment by partouf** [comment]
I'm very confused. It doesn't make any sense for it to use `tar` here. I tested the linux side of the windows installs just last week, so I guess it's some kind of weird logic going wrong when run via Windows? I'll have a look later today.

**Comment by OfekShilon** [comment]
@partouf  there's actually powershell on linux. Maybe somehow this runs on linux?

**Comment by partouf** [comment]
I did mostly write it on linux, hmm, maybe I intended to test it on Windows, but forgot?
