### ISSUE TITLE
[librarybuilding] clang parmexpr tbb build

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/infra#361]
```
2020-07-10 16:25:03,556 lib.installation INFO     Build succeeded in /tmp/staging/clang_parmexpr_49dd3e0e5ac73d30c1a96503111b7f2287dde14a010a2f165c7cf96d6644ef4b
readelf: Error: /tmp/staging/clang_parmexpr_49dd3e0e5ac73d30c1a96503111b7f2287dde14a010a2f165c7cf96d6644ef4b/libtbb.so: Failed to read file header
2020-07-10 16:25:03,746 lib.installation INFO     No binaries found to export
2020-07-10 16:25:04,222 lib.installation INFO     Building tbb for [clang_embed,-std=c++2a -stdlib=libc++,/opt/compiler-explorer/clang-embed-trunk-20200521,Linux,Debug,x86_64,c++2a,libc++,]
clean done
rm: cannot remove '*.so*': No such file or directory
rm: cannot remove '*.a': No such file or directory
2020-07-10 16:25:10,899 lib.installation INFO     Build succeeded in /tmp/staging/clang_embed_4e4b6c936381e88b13d4ea3bb28f42621d4748b29cc6de492ff1a7f3f4ee17df
2020-07-10 16:25:10,901 lib.installation INFO     No binaries found to export
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/build/infra/bin/lib/ce_install.py", line 209, in main
    [num_installed, num_skipped, num_failed] = installable.build(args.buildfor)
TypeError: cannot unpack non-iterable bool object
```

**Comment by partouf** [comment]
Ok, nothing special going on here. It just succeeded to build tbb for libstdc++ even though clang_parmexpr is libc++ only, so it really shouldn't have tried to build in the first place.
