### ISSUE TITLE
new rust installer failed for 1.39

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/infra#383]
```
install: copying file /opt/compiler-explorer/staging/rust-1.39.0/lib/rustlib/mips64-unknown-linux-gnuabi64/lib/libitertools-1d1c0b85cd51cafb.rlib
install: copying file /opt/compiler-explorer/staging/rust-1.39.0/lib/rustlib/mips64-unknown-linux-gnuabi64/lib/libcrossbeam_utils-152103c3f94bda4e.rlib
install: copying file /opt/compiler-explorer/staging/rust-1.39.0/lib/rustlib/mips64-unknown-linux-gnuabi64/lib/librustc_macros-8d8eec3bcd8ad0cf.so
install: copying file /opt/compiler-explorer/staging/rust-1.39.0/lib/rustlib/mips64-unknown-linux-gnuabi64/lib/libc2_chacha-c2c54440b8b94d19.rlib
install: copying file /opt/compiler-explorer/staging/rust-1.39.0/lib/rustlib/mips64-unknown-linux-gnuabi64/lib/libbyteorder-46afaadfc9acc908.rlib
install: copying file /opt/compiler-explorer/staging/rust-1.39.0/lib/rustlib/mips64-unknown-linux-gnuabi64/lib/libgetopts-3a6935c7ec3fc1b8.rlib
install: copying file /opt/compiler-explorer/staging/rust-1.39.0/lib/rustlib/mips64-unknown-linux-gnuabi64/lib/librustc_apfloat-602b0ea6bf26dafe.rlib
install: copying file /opt/compiler-explorer/staging/rust-1.39.0/lib/rustlib/mips64-unknown-linux-gnuabi64/lib/libcrossbeam_utils-83ef8f1a88866dc2.rlib
install: copying file /opt/compiler-explorer/staging/rust-1.39.0/lib/rustlib/mips64-unknown-linux-gnuabi64/lib/librustc_lexer-84210037d4d99d16.rlib
install: running ldconfig
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
install: WARNING: failed to run ldconfig. this may happen when not installing as root. run with --verbose to see the error

    std is standing at the ready.

2020-08-07 01:50:06,154 lib.installation INFO     Removing /opt/compiler-explorer/staging/__temp_install__
2020-08-07 01:50:06,547 lib.installation INFO     Fetching https://static.rust-lang.org/dist/rust-std-1.39.0-mips64el-unknown-linux-gnuabi64.tar.gz (223964211 bytes)
2020-08-07 01:50:38,758 lib.installation INFO     45.3% of https://static.rust-lang.org/dist/rust-std-1.39.0-mips64el-unknown-linux-gnuabi64.tar.gz...
2020-08-07 01:50:38,759 lib.installation INFO     100% of https://static.rust-lang.org/dist/rust-std-1.39.0-mips64el-unknown-linux-gnuabi64.tar.gz
2020-08-07 01:50:38,766 lib.installation INFO     Piping to tar zxf - --strip-components=1

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/matthew/dev/ce/infra/bin/lib/ce_install.py", line 178, in main
    if installable.install():
  File "/home/matthew/dev/ce/infra/bin/lib/installation.py", line 822, in install
    self.stage()
  File "/home/matthew/dev/ce/infra/bin/lib/installation.py", line 795, in stage
    self.do_rust_install(f'rust-std-{self.target_name}-{architecture}', base_path)
  File "/home/matthew/dev/ce/infra/bin/lib/installation.py", line 780, in do_rust_install
    self.install_context.fetch_url_and_pipe_to(url, ['tar', 'zxf', '-', '--strip-components=1'], untar_to)
  File "/home/matthew/dev/ce/infra/bin/lib/installation.py", line 118, in fetch_url_and_pipe_to
    subprocess.check_call(command, stdin=fd, cwd=str(untar_dir))
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tar', 'zxf', '-', '--strip-components=1']' returned non-zero exit status 2.
```

**Comment by partouf** [comment]
all the questionmarks in random spots on the screen, what?

**Comment by partouf** [comment]
> ```
> install: WARNING: failed to run ldconfig. this may happen when not installing as root. run with --verbose to see the error
> ```

Only a warning, but actually hilarious

**Comment by mattgodbolt** [comment]
Yeah hahaha :)

Seems like this was a transient thing, as I've just been poking it and it works just fine now. One thing to watch out for in future, maybe we need a retry in the `fetch`.
