### ISSUE TITLE
instances restart failed

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/infra#426]
```
INFO:ce:Moving i-06bd7d37876ece938@3.84.28.43 out of standby                                      
INFO:ce:Waiting for i-06bd7d37876ece938@3.84.28.43 to reach autoscale lifecycle 'InService'...    
INFO:ce:...done                                                                                   
INFO:ce:Waiting for i-06bd7d37876ece938@3.84.28.43 to reach ELB state 'healthy'...                
INFO:ce:...done                                                                                   
INFO:ce:Disabling instance protection for i-06bd7d37876ece938@3.84.28.43                          
INFO:ce:Instance restarted ok                                                                     
INFO:ce:Restarting i-09d62a8315e3c6ff4@34.207.157.198...                                          
Traceback (most recent call last):                                                                
  File "<string>", line 1, in <module>                                                            
  File "/home/ubuntu/infra/bin/lib/ce.py", line 932, in main                                      
    globals()[cmd + "_cmd"](kwargs)                                                               
  File "/home/ubuntu/infra/bin/lib/ce.py", line 270, in instances_cmd                             
    dispatch_global('instances', args)                                                            
  File "/home/ubuntu/infra/bin/lib/ce.py", line 36, in dispatch_global                            
    globals()['{}_{}_cmd'.format(sub, args['{}_sub'.format(sub)])](args)                          
  File "/home/ubuntu/infra/bin/lib/ce.py", line 322, in instances_restart_cmd                     
    as_instance_status = instance.describe_autoscale()                                            
  File "/home/ubuntu/infra/bin/lib/instance.py", line 25, in describe_autoscale                   
    return results['AutoScalingInstances'][0]                                                     
IndexError: list index out of range                                                               
Oct/20 12:48 admin-node~/infra (master|✔) 10.4m $                                                 
```

was just a `ce --env prod instances restart`

I suspect an autoscaling event happened while the upgrade ran.

**Comment by mattgodbolt** [comment]
One instance was left in the old version:

```
Oct/20 12:48 admin-node~/infra (master|✔) 10.4m $ ce --env prod instances status                    
Running in prod                                                                                     
Address          Instance Id          State      Type         ELB         Service     Version       
54.164.73.138    i-022f33bd2487102ab  running    c5.large     healthy     running     6509 (master) 
3.238.25.42      i-09466d56ec80abaf6  running    c5.large     healthy     running     6509 (master) 
3.209.11.211     i-04099c9deb9279c9a  running    c5.large     healthy     running     6509 (master) 
3.87.141.234     i-0bbda0255bf2ff74e  running    c5.large     healthy     running     6509 (master) 
3.208.24.70      i-0482552e4cf1f8d20  running    c5.large     healthy     running     6505 (master) 
54.242.27.83     i-08357fdf8393b58d3  running    c5.large     healthy     running     6509 (master) 
```

will manually restart.

**Comment by mattgodbolt** [comment]
It just happened again; argh.
