### ISSUE TITLE
Log or detect errors earlier in library build process

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/infra#543]
Build errors get logged the https://conan.compiler-explorer.com/failedbuilds.html
But if a different part of the buildprocess, say conan for example, gives errors, the builder will simply stop because of the error (example: https://github.com/compiler-explorer/infra/pull/542), and the error won't end up somewhere useful.

It's also not visible in papertrail, but I wouldn't want to put more useless logging into that either.

Is there any way to log only when an error occurs or alert us? https://github.com/compiler-explorer/infra/blob/main/admin-daily-builds.sh#L98

@mattgodbolt @apmorton

**Comment by mattgodbolt** [comment]
(current build fails with:

```
Status: Downloaded newer image for compilerexplorer/library-builder:latest
+ LIBRARYTOBUILD=all
+ FORCECOMPILER=all
+ FORCECOMPILERPARAM=
+ '[' all '!=' all ']'
+ LIBRARYPARAM=libraries/c++
+ '[' all '!=' all ']'
++ pwd
+ ROOT=/tmp/build
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/compiler-explorer/cmake/bin
+ cd /tmp/build
+ git clone https://github.com/compiler-explorer/infra
Cloning into 'infra'...
+ cd /tmp/build/infra
+ cp /tmp/build/infra/init/settings.yml /root/.conan/settings.yml
+ make ce
  Failed building wheel for boto3
  Failed building wheel for aiohttp
  Failed building wheel for wrapt
  Failed building wheel for multidict
  Failed building wheel for yarl
Command "/tmp/build/infra/.env/bin/python3.8 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-wfvev0y1/multidict/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-lsr6_e6o-record/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/build/infra/.env/include/site/python3.8/multidict" failed with error code 1 in /tmp/pip-build-wfvev0y1/multidict/
make: *** [.env] Error 1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/infra/bin/lib/ce.py", line 1057, in main
    cli(prog_name='ce')  # pylint: disable=unexpected-keyword-arg,no-value-for-parameter
  File "/home/ubuntu/infra/.env/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/infra/.env/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/infra/.env/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/infra/.env/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/infra/.env/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
```
)

**Comment by mattgodbolt** [comment]
(which is on me)

**Comment by partouf** [comment]
Just started buildscript manually to build Gcc 11.2.0, but it failed on `ce builder start`
2nd attempt about a minute later succeeded

**Comment by partouf** [comment]
Uhhh and now it looks to be stuck

**Comment by partouf** [comment]
Note that last builder run for any other compiler has been 4 days ago https://godbolt.org/admin/builds.html

**Comment by partouf** [comment]
> Uhhh and now it looks to be stuck

the builder had randomly stopped, maybe because of the failing start earlier

**Comment by partouf** [comment]
```
Jul/28 13:15 admin-node/tmp 6.6s $ ce builder start
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/infra/bin/lib/ce.py", line 1150, in main
    cli(prog_name='ce')  # pylint: disable=unexpected-keyword-arg,no-value-for-parameter
  File "/home/ubuntu/infra/.env/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/infra/.env/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/infra/.env/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/infra/.env/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/infra/.env/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/infra/.env/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/infra/bin/lib/ce.py", line 323, in builder_start
    r = exec_remote(instance, ["echo", "hello"])
  File "/home/ubuntu/infra/bin/lib/ssh.py", line 62, in exec_remote
    with ssh_client_for(instance) as client:
  File "/home/ubuntu/infra/bin/lib/ssh.py", line 95, in ssh_client_for
    client.connect(hostname=ssh_address_for(instance), username='ubuntu', timeout=5)
  File "/home/ubuntu/infra/.env/lib/python3.8/site-packages/paramiko/client.py", line 397, in connect
    our_server_keys = self._system_host_keys.get(server_hostkey_name)
  File "/usr/lib/python3.8/_collections_abc.py", line 660, in get
    return self[key]
  File "/home/ubuntu/infra/.env/lib/python3.8/site-packages/paramiko/hostkeys.py", line 245, in __getitem__
    ret = self.lookup(key)
  File "/home/ubuntu/infra/.env/lib/python3.8/site-packages/paramiko/hostkeys.py", line 191, in lookup
    if self._hostname_matches(hostname, e):
  File "/home/ubuntu/infra/.env/lib/python3.8/site-packages/paramiko/hostkeys.py", line 207, in _hostname_matches
    and not hostname.startswith("|1|")
AttributeError: 'NoneType' object has no attribute 'startswith'

```

**Comment by partouf** [comment]
This last one might be because i force terminated the instance on AWS because it wasn't responding. How do we get it back to normal?

**Comment by partouf** [comment]
Starting 2nd attempt, recreated builder instance based on previous version.

(for future: Note that it still uses a 2018 AMI and infra is still called compiler-explorer-image and required some manual hacking to get right)

**Comment by partouf** [comment]
it has randomly stopped again, but at a later moment

**Comment by partouf** [comment]
now stuck in stopping state
