### ISSUE TITLE
ofw nightly fails to install

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/infra#677]
```
Installing libraries/c++/nightly/ofw trunk
2022-02-14 04:34:54,514 lib.installation INFO     libraries/c++/nightly/ofw trunk failed to install: Command '['git', '-C', '/opt/compiler-explorer/libs/ofw/trunk', 'fetch', '-q']' returned non-zero exit status 128.
Traceback (most recent call last):
  File "/home/ubuntu/infra/bin/lib/ce_install.py", line 192, in main
    if installable.install():
  File "/home/ubuntu/infra/bin/lib/installation.py", line 557, in install
    self.stage()
  File "/home/ubuntu/infra/bin/lib/installation.py", line 538, in stage
    self.clone_default()
  File "/home/ubuntu/infra/bin/lib/installation.py", line 516, in clone_default
    subprocess.check_call(['git', '-C', dest, 'fetch', '-q'], cwd=self.install_context.staging)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', '-C', '/opt/compiler-explorer/libs/ofw/trunk', 'fetch', '-q']' returned non-zero exit status 128.
```

Seemingly related:
```
fatal: could not read Username for 'https://github.com/': No such device or address
```

**Comment by apmorton** [comment]
fixed in https://github.com/compiler-explorer/infra/commit/4f891ca2255ff4e375c20cccebb260cb8334d4fd
