### ISSUE TITLE
squashfs broken since my recent changes

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/infra#816]
```
2022-09-21 06:38:55,683 lib.ce_install  INFO     Skipping compilers/d/ldc 1.3.0 as it already exists at /opt/squash-images/ldc1.3.0.img
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/opt/actions-runner/_work/infra/infra/bin/lib/ce_install.py", line 302, in _to_squash
    if not installable.is_installed():
  File "/opt/actions-runner/_work/infra/infra/bin/lib/installation.py", line 402, in is_installed
    binary.chmod(0o755)
  File "/usr/lib/python3.8/pathlib.py", line 1306, in chmod
    self._accessor.chmod(self, mode)
PermissionError: [Errno 1] Operation not permitted: '/opt/compiler-explorer/gcc-4.9.4/bin/g++'
"""
```

**Comment by mattgodbolt** [comment]
Ah, it was the Odin changes. They attempt to `chmod` things and when we're squashing we're not root and don't have permission. Will fix.
