### ISSUE TITLE
ce_install --cache broken

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/infra#817]
```
$ ce_install --cache ~/.web_cache install odin dev-2022-08
2022-09-21 17:17:20,703 lib.installation INFO     Using cache /home/matthew/.web_cache
2022-09-21 17:17:20,704 lib.ce_install  INFO     Creating multiprocessing pool with 8 workers
Installing compilers/odin dev-2022-08
2022-09-21 17:17:23,852 lib.ce_install  INFO     compilers/odin dev-2022-08 failed to install: 'CacheControlAdapter' object has no attribute 'cacheable_methods'
Traceback (most recent call last):
  File "/home/matthew/dev/ce/infra/bin/lib/ce_install.py", line 391, in install
    installable.install()
  File "/home/matthew/dev/ce/infra/bin/lib/installation.py", line 893, in install
    self.stage(staging)
  File "/home/matthew/dev/ce/infra/bin/lib/installation.py", line 868, in stage
    self.install_context.fetch_to(self.url, fd)
  File "/home/matthew/dev/ce/infra/bin/lib/installation.py", line 115, in fetch_to
    request = self.fetcher.get(url, stream=True)
  File "/home/matthew/dev/ce/infra/.env/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
AttributeError: 'CacheControlAdapter' object has no attribute 'cacheable_methods'
```

**Comment by mattgodbolt** [comment]
I've just had it work... and then not work... on the same machine! Mystery deepens

**Comment by mattgodbolt** [comment]
But now it's consistently bad.
