### ISSUE TITLE
beta environment is broken

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/infra#962]
```js
Mar 10 03:40:44Z [ip-172-30-1-69](https://my.papertrailapp.com/systems/ip-172-30-1-69/events?focus=1570693122362195999&selected=1570693122362195999) [amazon.beta](https://my.papertrailapp.com/groups/1243314/events?q=program%3Aamazon.beta&focus=1570693122362195999&selected=1570693122362195999)  error: Exception while processing compilers: Could not load credentials from any providers {"$metadata":{"attempts":1,"totalRetryDelay":0},"name":"CredentialsProviderError","stack":"CredentialsProviderError: Could not load credentials from any providers\n    at /infra/.deploy/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js:13:11\n    at /infra/.deploy/node_modules/@aws-sdk/property-provider/dist-cjs/chain.js:11:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async coalesceProvider (/infra/.deploy/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:14:24)\n    at async SignatureV4.credentialProvider (/infra/.deploy/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:33:24)\n    at async SignatureV4.signRequest (/infra/.deploy/node_modules/@aws-sdk/signature-v4/dist-cjs/SignatureV4.js:87:29)\n    at async /infra/.deploy/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:16:18\n    at async /infra/.deploy/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46\n    at async /infra/.deploy/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:58:20\n    at async /infra/.deploy/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22","tryNextLink":false}
```

**Comment by mattgodbolt** [comment]
no, I broke SSM!
