### ISSUE TITLE
llvm trunk failing to install

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/infra#980]
May be unlucky that an install is already going but:

```
Installing libraries/c++/nightly/llvm trunk
2023-03-28 12:30:52,522 lib.installation_context INFO     Fetching https://s3.amazonaws.com/compiler-explorer/opt/llvm-trunk-20230328.tar.xz (3231052 bytes)
2023-03-28 12:30:52,647 lib.installation_context INFO     100% of https://s3.amazonaws.com/compiler-explorer/opt/llvm-trunk-20230328.tar.xz
2023-03-28 12:30:52,647 lib.installation_context INFO     Piping to tar Jxf -
2023-03-28 12:31:59,213 lib.installation_context INFO     Removing libs/llvm/llvm-trunk-20230322
2023-03-28 12:31:59,217 lib.installation_context INFO     Moving from staging (/opt/compiler-explorer/staging/a5d6e566-750b-499e-92bf-6dbf69b41ce3/llvm-trunk-20230328) to final destination (/opt/compiler-explorer
/libs/llvm/llvm-trunk-20230328)
2023-03-28 12:32:08,636 lib.installation_context INFO     Destination /opt/compiler-explorer/libs/llvm/llvm-trunk-20230328 exists, temporarily moving out of the way (to /opt/compiler-explorer/staging/a5d6e566-750
b-499e-92bf-6dbf69b41ce3/temp_orig)
2023-03-28 12:32:20,147 lib.installation_context INFO     Symlinking llvm-trunk-20230328 to /opt/compiler-explorer/libs/llvm/trunk
2023-03-28 12:32:20,172 lib.ce_install  INFO     libraries/c++/nightly/llvm trunk failed to install: [Errno 17] File exists: 'llvm-trunk-20230328' -> '/opt/compiler-explorer/libs/llvm/trunk'
Traceback (most recent call last):
  File "/home/ubuntu/infra/bin/lib/ce_install.py", line 393, in install
    installable.install()
  File "/home/ubuntu/infra/bin/lib/installable/archives.py", line 134, in install
    self.install_context.set_link(Path(self.install_path), self.path_name_symlink)
  File "/home/ubuntu/infra/bin/lib/installation_context.py", line 164, in set_link
    full_dest.symlink_to(relative_source)
  File "/usr/lib/python3.10/pathlib.py", line 1255, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
FileExistsError: [Errno 17] File exists: 'llvm-trunk-20230328' -> '/opt/compiler-explorer/libs/llvm/trunk'

```

Just had this

**Comment by mattgodbolt** [comment]
removed symlink and reran. all ok
